### PR TITLE
Fix #5: Override serde_json's `preserve_order` behaviour

### LINKED ISSUE #5: Keys are in wrong order if `preserve_order` feature is active in `serde_json`
I've got two services using `canonical_json` to output some JSON for signing.  Unfortunately, they disagree on the order of keys in their output.  One of them correctly outputs in lexicographical order, one of them does not.

I've tracked this down to the `preserve_order` feature flag in `serde_json`.  If this is present then `serde_json::map::Map` [uses an `IndexMap` rather than a `BTreeMap`](https://github.com/serde-rs/json/blob/master/src/map.rs#L23-L26), and it seems `canonical_json` relies on this `BTreeMap` to output data in the correct order.

This would be relatively easy to fix if I'd requested the `preserve_order` flag myself but I didn't.  There's a transient dependency somewhere in my tree that's requested it...

### PR DESCRIPTION
**Pull request by leplatrem**
Fix #5

### CODE REVIEW

File: src/ser.rs [hunk 1]
```diff
@@ -435,4 +463,22 @@ mod tests {
             r#"[{"foo":"bar","id":"1","last_modified":"12345"},{"bar":"baz","id":"2","last_modified":"45678"}]"#
         );
     }
+
+    #[test]
+    fn test_keys_sorted_regardless_of_preserve_order() {
+        // Canonical JSON requires lexicographically sorted keys. to_string() must sort
+        // keys even when serde_json's preserve_order feature is enabled (which uses
+        // IndexMap and retains insertion order instead of sorting).
+        let mut map = serde_json::Map::new();
```
Comment (alexcottner) [inline src/ser.rs:472]: I think we need a far more complex object to know that this is working as expected. Nested objects, arrays of objects that have their own arrays of strings, etc.

Comment (leplatrem) [reply src/ser.rs:472]: I added a full test file, using the serializer from the `main` branch:

```
$ git co main
$ cd demo/
$ cargo build
$ curl https://firefox.settings.services.mozilla.com/v1/buckets/main/collections/search-config-v2/changeset\?_expected\=0 | jq > testsuite/search-config-v2.json
$ ./target/debug/demo ../testsuite/search-config-v2.json > ../testsuite/search-config-v2.canonical.json
```

Comment (alexcottner) [reply src/ser.rs:472]: very nice

**Review by alexcottner — APPROVED** [review]
